#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const PROMPTS = path.join(ROOT, "prompts");
const SCHEMAS = path.join(ROOT, "schemas");
const OUT = path.join(ROOT, "dist/codex/.codex");
const AGENTS_OUT = path.join(OUT, "agents");

const agents = [
  {
    name: "pm-agent",
    prompt: "pm",
    schema: "pm",
    description:
      "Pragmatic PM for the Startup Advisor Board. Scopes the MVP and names riskiest assumptions. Returns PMOutput JSON.",
    nickname_candidates: ["PM Scout", "Scope Lead", "MVP Lens"],
  },
  {
    name: "engineer-agent",
    prompt: "engineer",
    schema: "engineer",
    description:
      "Senior engineer for the Startup Advisor Board. Proposes the simplest architecture after PM scope. Returns EngineerOutput JSON.",
    nickname_candidates: ["Build Lead", "Architecture Lens", "Tech Scout"],
  },
  {
    name: "user-evaluator-agent",
    prompt: "user-evaluator",
    schema: "user-evaluator",
    description:
      "UX evaluator for the Startup Advisor Board. Finds friction, magic moments, and retention hooks. Returns UserEvalOutput JSON.",
    nickname_candidates: ["UX Lens", "Friction Finder", "User Scout"],
  },
  {
    name: "critic-agent",
    prompt: "critic",
    schema: "critic",
    description:
      "Skeptical critic for the Startup Advisor Board. Names the hard truth and what to cut. Returns CriticOutput JSON.",
    nickname_candidates: ["Reality Check", "Risk Lens", "Cut Lead"],
  },
  {
    name: "synthesizer-agent",
    prompt: "synthesizer",
    schema: "final-plan",
    description:
      "Senior partner for the Startup Advisor Board. Reconciles all specialist outputs into FinalPlan JSON.",
    nickname_candidates: ["Synthesis Lead", "Final Plan", "Partner Lens"],
  },
  {
    name: "startup-advisor-orchestrator",
    prompt: "orchestrator",
    schema: null,
    description:
      "Orchestrates the Startup Advisor Board by spawning PM, Engineer, User Evaluator, Critic, and Synthesizer subagents with isolated contexts.",
    nickname_candidates: ["Advisor Board", "Board Chair", "Orchestrator"],
  },
];

function tomlString(value) {
  return JSON.stringify(value);
}

function tomlStringArray(values) {
  return `[${values.map(tomlString).join(", ")}]`;
}

function tomlMultilineLiteral(value) {
  if (value.includes("'''")) {
    throw new Error("Cannot emit TOML literal string containing triple single quotes");
  }
  return `'''\n${value.replace(/\s+$/u, "")}\n'''`;
}

function promptWithSchema(agent) {
  let body = fs.readFileSync(path.join(PROMPTS, `${agent.prompt}.md`), "utf8");

  if (agent.schema) {
    const schemaPath = path.join(SCHEMAS, `${agent.schema}.schema.json`);
    const schemaJson = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
    const block = "```json\n" + JSON.stringify(schemaJson, null, 2) + "\n```";
    if (!body.includes("{schema}")) {
      throw new Error(`prompts/${agent.prompt}.md is missing the {schema} placeholder`);
    }
    body = body.replace("{schema}", block);
  }

  return body;
}

function codexInstructions(agent) {
  let body = promptWithSchema(agent);

  if (agent.name === "startup-advisor-orchestrator") {
    const schemaNames = ["pm", "engineer", "user-evaluator", "critic", "final-plan"];
    const schemaBlocks = schemaNames
      .map((name) => {
        const schemaPath = path.join(SCHEMAS, `${name}.schema.json`);
        const schemaJson = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
        return `### ${name}.schema.json\n\n\`\`\`json\n${JSON.stringify(schemaJson, null, 2)}\n\`\`\``;
      })
      .join("\n\n");

    body += `\n\n## Codex packaging notes\n\n- Invoke the specialist custom subagents by exact name: \`pm-agent\`, \`engineer-agent\`, \`user-evaluator-agent\`, \`critic-agent\`, and \`synthesizer-agent\`.\n- Each specialist invocation must be a separate subagent run with its own context window. Do not simulate a specialist in this orchestrator context.\n- Use the embedded schemas below for validation; do not assume the target project has this repository's \`schemas/\` directory.\n\n## Embedded validation schemas\n\n${schemaBlocks}`;
  }

  return body;
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(AGENTS_OUT, { recursive: true });

const config = `# Generated by hosts/codex/build.mjs.
# Copy this directory to a project root so Codex can load the Startup Advisor Board subagents.

[agents]
max_threads = 8
max_depth = 2

${agents
  .map(
    (agent) => `[agents.${tomlString(agent.name)}]
config_file = ${tomlString(`agents/${agent.name}.toml`)}`
  )
  .join("\n\n")}
`;

fs.writeFileSync(path.join(OUT, "config.toml"), config);
console.log(`wrote ${path.relative(ROOT, path.join(OUT, "config.toml"))}`);

for (const agent of agents) {
  const body = codexInstructions(agent);
  const lines = [
    "# Generated by hosts/codex/build.mjs. Do not edit this file directly.",
    `name = ${tomlString(agent.name)}`,
    `description = ${tomlString(agent.description)}`,
    `nickname_candidates = ${tomlStringArray(agent.nickname_candidates)}`,
    "developer_instructions = " + tomlMultilineLiteral(body),
    "",
  ];

  const outPath = path.join(AGENTS_OUT, `${agent.name}.toml`);
  fs.writeFileSync(outPath, lines.join("\n"));
  console.log(`wrote ${path.relative(ROOT, outPath)}`);
}

console.log(`\nDone. Copy ${path.relative(ROOT, OUT)}/ into your project's .codex/ directory.`);
